### ISSUE TITLE
dockWebLogic cannot find developer image

### ISSUE THREAD

**Issue by bradlund** [weblogic-community/weblogic-docker#11]
submitting this as an issue because I don't know quite enough about this ecosystem yet to give a pull request.

I was following  the steps as outlined in https://github.com/weblogic-community/weblogic-docker/blob/master/README.md.   I copied the jdk rpm and the wls zip into the developer folder, and ran 
    sudo buildDockerImage.sh -d

This completed successfully:

    vagrant@vagrant-ubuntu-trusty-64:/vagrant/docker/weblogic-docker/bin$ sudo docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
    oracle/weblogic     12.1.3-dev          c072b1434b13        About a minute ago   2.144 GB
    oraclelinux         7.0                 073ded22ac0f        12 days ago          265.2 MB

But when i ran dockWebLogic.sh -a, I got the following error:

    vagrant@vagrant-ubuntu-trusty-64:/vagrant/docker/weblogic-docker/bin$ sudo ./dockWebLogic.sh -a
    Unable to find image 'oracle/weblogic:12.1.3' locally
    Pulling repository oracle/weblogic
    FATA[0000] Error: image oracle/weblogic:12.1.3 not found

It's looking for 12.1.3 and I have 12.1.3-dev.

I chose to get around this by adding a -d flag to ./dockWebLogic.sh to indicate to get the correct IMAGE_NAME for the developer environment from the setDockerEnv script. 

![2015-01-13_17-33-19](https://cloud.githubusercontent.com/assets/876866/5731216/2f76d22a-9b4f-11e4-8ca9-bfb83f93a5a3.png)

This worked, but I'm not sure it's the intended usage, or if i'm misunderstanding how the scripts work together.

**Comment by brunoborges** [comment]
Yeap! That's the intended usage. Feel free to do a pull request!

**Comment by brunoborges** [comment]
Fixed by 0e642531d9
