### ISSUE TITLE
Could not find or load main class org.apache.tools.ant.Main

### ISSUE THREAD

**Issue by dre32722** [weblogic-community/weblogic-docker#12]
Hi,
I notice that someone else commented on this issue but didnt post an issue associated with this project. Refer https://blogs.oracle.com/brunoborges/entry/docker_java_ee_7_and . 

I have found the same issue when executing /bin/buildDockerImage.sh  .
I get the following error reported during Step 19...
....
Step 19 : RUN sh configure.sh -silent &&     /u01/oracle/weblogic/wlserver/common/bin/wlst.sh -skipWLSModuleScanning /u01/create-wls-domain.py &&     mkdir -p /u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/security &&     mv /u01/commEnv.sh /u01/oracle/weblogic/wlserver/common/bin/commEnv.sh &&     echo "username=weblogic" > /u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> /u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties &&     rm /u01/create-wls-domain.py /u01/$WLS_PKG /u01/jaxrs2-template.jar &&     echo ". /u01/oracle/weblogic/user_projects/domains/base_domain/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     echo "export PATH=$PATH:/u01/oracle/weblogic/wlserver/common/bin:/u01/oracle/weblogic/user_projects/domains/base_domain/bin" >> /u01/oracle/.bashrc
 ---> Running in aabdda1739a2
Error: Could not find or load main class org.apache.tools.ant.Main

WebLogic Docker Container is ready to be used. To start, run 'dockWebLogic.sh'

Although it says it is ready to be used it doesn’t run --- presumably because of the above error ????
[root@manunited bin]# ./dockWebLogic.sh
Unable to find image 'oracle/weblogic:12.1.3' locally
Pulling repository oracle/weblogic
2015/01/14 12:20:49 Error: image oracle/weblogic not found

Any help appreciated.
regards
Dave

**Comment by brunoborges** [comment]
What Host OS are you using?

**Comment by dre32722** [comment]
Oracle Linux 3.8.13-35.3.4.el6uek.x86_64
[root@manunited /]# docker version
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f/1.3.3
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f/1.3.3

**Comment by brunoborges** [comment]
Oh, the reason is you built one image, and you are trying to run another one. Check the scripts and variables.

**Comment by brunoborges** [comment]
Unable to find image 'oracle/weblogic:12.1.3' locally
Pulling repository oracle/weblogic
2015/01/14 12:20:49 Error: image oracle/weblogic not found

**Comment by dre32722** [comment]
ok --- I am new to this, so not sure what you are recommending I do.
My build failed due to the missing ant  error ... however the message at the end of the process suggested that it completed successfully ...WebLogic Docker Container is ready to be used. To start, run 'dockWebLogic.sh'

How do I resolve the missing ant issue so I can get a successful build ?

Also if the output of docker images and docker info (as per cut and paste below), how should I proceed / tidy this up? Should I unload ? I dont see a command allowing me to do so ...

[root@manunited ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
oracle/weblogic     12.1.3-dev          78276072fb9c        45 hours ago        2.144 GB
oraclelinux         7                   073ded22ac0f        2 weeks ago         265.2 MB
oraclelinux         latest              073ded22ac0f        2 weeks ago         265.2 MB
oraclelinux         7.0                 5f1be1559ccf        9 weeks ago         265.2 MB

[root@manunited ~]# docker info
Containers: 2
Images: 30
Storage Driver: devicemapper
 Pool Name: docker-252:0-917952-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 2.858 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 3.072 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.8.13-35.3.4.el6uek.x86_64
Operating System: <unknown>

**Comment by brunoborges** [comment]
You can safely ignore the Ant error. 

But to run the image, you must point to the correct image. In your 'docker images' list you have a "oracle/weblogic:12.1.3-dev". But you are running dockWebLogic.sh without adjusting the image name, and thus the script loads the default name which is "oracle/weblogic:12.1.3" (without -dev), which tries to run the Generic image.

Check latest commit 0e642531d9. Run "dockWebLogic.sh -d"
