### ISSUE TITLE
container-scripts folder seems to be missing

### ISSUE THREAD

**Issue by peterboldizs** [weblogic-community/weblogic-docker#19]
Greetings,

When I execute the build script found in the bin folder (renamed to buildDockerImage.sh at the time of my git checkout), I get the following error message:

Step 12 : ADD container-scripts/* /u01/
2015/01/20 15:44:37 container-scripts/*: no such file or directory

WebLogic Docker Container was NOT successfully created. Check the output and correct any reported problems with the docker build operation.

When I list the contents of the corresponding directory, I get this:
peter@ubuntuboldizs:~/git/weblogic-docker/weblogic12c-developer$ ls
container-scripts  Dockerfile  jdk-8u25-linux-x64.rpm  README.md  wls1213_dev.zip

So the container-scripts folder seems to be present but the step in the Dockerfile ignores it. Could you please help?

**Comment by brunoborges** [comment]
How are you executing the buildDockerImage.sh script?

**Comment by peterboldizs** [comment]
I am in the main directory and running it using the following:
peter@ubuntuboldizs:~/git/weblogic-docker$ sudo bin/buildDockerImage.sh -d

I have also tried to run in from the bin directory:
peter@ubuntuboldizs:~/git/weblogic-docker/bin$ sudo ./buildDockerImage.sh -d
I did not work either. Hope that helps.

**Comment by brunoborges** [comment]
Please, checkout latest version.

Then go to the bin folder, become root, then run:
    $ sh buildDockerImage.sh -d

Let me know if this works.

**Comment by peterboldizs** [comment]
I have tried the following:

peter@ubuntuboldizs:~/git/weblogic-docker/bin$ git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 3), reused 2 (delta 0)
Unpacking objects: 100% (5/5), done.
From https://github.com/weblogic-community/weblogic-docker
   2ff795c..03509d6  master     -> origin/master
Updating 2ff795c..03509d6
Fast-forward
 bin/dockNodeManager.sh | 14 +++++++++-----
 bin/dockWebLogic.sh    | 19 ++++++++++++-------
 2 files changed, 21 insertions(+), 12 deletions(-)
peter@ubuntuboldizs:~/git/weblogic-docker/bin$ sudo sh buildDockerImage.sh -d

(Also tried this:
peter@ubuntuboldizs:~/git/weblogic-docker/bin$ sudo ./buildDockerImage.sh -d
)

Unfortunately, I did not work either. I have the following system:
OS:
Ubuntu 14.04.1 LTS
Docker:
peter@ubuntuboldizs:~/git/weblogic-docker/bin$ sudo docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a

**Comment by brunoborges** [comment]
Oh, you have a very outdated Docker version. Please upgrade it. :-)

**Comment by peterboldizs** [comment]
Thanks, I will definitely upgrade it. I have installed this today using apt-get install docker.io
I am new to Docker and I was not aware of the need to upgrade it.
Thanks.

**Comment by brunoborges** [comment]
Fixed by simply upgrading to a newer version of Docker :-)
