### ISSUE TITLE
MD5 check fails in build script

### ISSUE THREAD

**Issue by peterboldizs** [weblogic-community/weblogic-docker#20]
I have downloaded the jdk-8u25-linux-x64.rpm from the proper location:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html 
I have manually run the MD5 checksum and it seemed identical to the one found on this page:
https://www.oracle.com/webfolder/s/digest/8u25checksum.html

However, the script has still failed when executed the corresponding lines:
if ! check_md5 $JAVA_PKG $JAVA_PKG_MD5
then
  echo "MD5 for $JAVA_PKG does not match! Download again!"
  exit
fi

To eliminate this problem, I have commented the above out and it went through.
This is not an ideal solution - could you please help

**Comment by brunoborges** [comment]
Fixed with  2ff795c5c0
